### ISSUE TITLE
 EAS build --platform all Error: Input is required, but stdin is not readable on IOS

### ISSUE THREAD

**Issue by kelvinndmo** [expo/expo-github-action#106]
### Description of the bug
Am trying to build and app using Github Actions then probably distribute it to the store, so far everything except the part where it prompts me if i want to login to my Apple account, The action the goes ahead and throw an error ```Input is required, but stdin is not readable``` probably because of the same.

### To Reproduce
What steps did you perform which led to this issue?
Configure the action as shown below.
The build will be successful for Android.

On the terminal, I get this prompt which is definately not available on the action, am using an app specific password
```

```
```
name: Publish to Testflight

on:
  workflow_dispatch:
    release:
      types: [created]

jobs:
  build:
    name: Create new build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: eas build --platform all
        env:
          EXPO_APPLE_ID: ${{secrets.EXPO_APPLE_ID}}
          EXPO_APPLE_ID_PASSWORD: ${{secrets.EXPO_APPLE_ID_PASSWORD}}
```

#### Expected behavior
- Build ios app

#### Actual behavior
Excited with an error

### Additional context
Can you further explain the issue? E.g., information about version/environment or screenshots.
![Screenshot 2021-07-30 at 12 28 59](https://user-images.githubusercontent.com/32582512/127632847-8c249936-d7c7-44d7-976c-ce1110d2ed11.png)
