### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by GautierT** [expo/expo-github-action#113]
### Description of the bug
It took a long time to publish a new version from the starting of the metro bundler to the complete bundle.  (8 minutes)

### To Reproduce
What steps did you perform which led to this issue?

Use this workflow 

```
name: Expo Publish Prod
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: npm install
      - run: APP_ENV=production expo publish --release-channel prod
```

#### Expected behavior
It's very fast on local (max 1 minutes)

#### Actual behavior

It take 8 minutes on github actions

### Additional context

The cache is activated with the `expo-cache` option

LOGS : 
> APP_ENV=production expo publish --release-channel prod

[10:14:02] › Expo SDK: 41.0.0
[10:14:02] › Release channel: prod
[10:14:02] › Workflow: Managed

[10:14:02] Building optimized bundles and generating sourcemaps...
[10:14:04] Starting Metro Bundler
[10:22:10] iOS Bundling complete 486190ms
[10:22:10] 
[10:22:10] Bundle                     Size
┌ index.ios.js          5.47 MB
├ index.android.js      5.49 MB
├ index.ios.js.map      14.6 MB
└ index.android.js.map  14.7 MB
[10:22:10]
