### ISSUE TITLE
Patching system watchers for the `ENOSPC` error when running expo/expo-github-action@v6

### ISSUE THREAD

**Issue by javascripter** [expo/expo-github-action#133]
### Description of the bug
expo-github-action fails with `Error: Error: The process '/usr/local/bin/yarn' failed with exit code null` when running on GitHub Actions. Updating node to 16.x did not solve the issue.
https://github.com/expo/expo-github-action/issues/132#issuecomment-992245294

Also, I tried `patch-watchers: false` but it resulted in an error as well. With `patch-watchers: false`, the below error was thrown with no detailed info.
```
Error: Error: The process '/usr/local/bin/yarn' failed with exit code null
```

### To Reproduce
Running the below workflow on GitHub Actions.
```
name: EAS build
on:
  workflow_dispatch:

jobs:
  build:
    name: Create new build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
```

#### Expected behavior
Runs without errors.
#### Actual behavior
The action fails with the following error:
```
Run expo/expo-github-action@v6
  with:
    expo-version: latest
    eas-version: latest
    token: ***
    expo-cache: false
    eas-cache: false
    packager: yarn
    patch-watchers: true
Installing expo-cli (5.0.3) with yarn
Installing eas-cli (0.43.0) with yarn
Checking current authenticated account
Patching system watchers for the `ENOSPC` error
  Patching system watchers for the `ENOSPC` error...
  /usr/bin/sudo sysctl fs.inotify.max_user_instances=524288
  Error: Error: The process '/usr/local/bin/yarn' failed with exit code null
  fs.inotify.max_user_instances = 524288
  /usr/bin/sudo sysctl fs.inotify.max_user_watches=524288
  fs.inotify.max_user_watches = 524288
  /usr/bin/sudo sysctl fs.inotify.max_queued_events=524288
  fs.inotify.max_queued_events = 524288
  /usr/bin/sudo sysctl -p
  vm.max_map_count = 262144
```

### Additional context
We did not experience this error last night. I'm not actually sure if this is caused by expo-github-action, some changes to GitHub Actions, or our repo. At the moment we run eas build locally but would like to be able to build via GitHub Actions.
