### ISSUE TITLE
EAS submit fails in Github Action

### ISSUE THREAD

**Issue by maticzav** [expo/expo-github-action#135]
### Description of the bug
I am trying to use `expo-github-action` to automate submission of apps to EAS, but `eas-cli` is reporting an error

```
Error: Input is required, but stdin is not readable.
```

I am using remote/managed credentials from Expo server.

### To Reproduce

I am using the following action configuration

```
name: Publish to App Store

on:
  push:
    branches:
      - main
    paths:
      - app/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Setup Expo CLI
        uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn workspaces focus petka
      - name: Publish using Expo CLI
        run: cd app && eas build -p ios --auto-submit
```

#### Expected behavior

I am not sure if I missed something in the docs, but I assumed this would've built and uploaded the iOS app to the EAS server.
