### ISSUE TITLE
Action stucks at publish

### ISSUE THREAD

**Issue by kuriel-trivu** [expo/expo-github-action#136]
### Description of the bug
Action stucks at publish command.
`expo publish --release-channel stg`

### To Reproduce
This is what i'm using at Github action yaml file:

```
name: Expo Publish
on:
  push:
    branches:
      - stg
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
    
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
      
    - name: Publish
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - uses: expo/expo-github-action@v6
      with:
        expo-version: 4.x
        expo-cache: true
        token: ${{ secrets.EXPO_TOKEN }}
    - run: yarn install
    - run: expo publish --release-channel ${{ steps.extract_branch.outputs.branch }}

```

#### Expected behavior
Continue and finish publishing.

#### Actual behavior
Everything before publish runs ok, but after that it stucks at `Starting Metro Bundler` log

![image](https://user-images.githubusercontent.com/46456105/148720789-ba5888e2-b875-40b9-85bb-82a63e7f1d54.png)

### Additional context
First Time of proyect running Expo with Github Actions to publish.

**Comment by kuriel-trivu** [comment]
After a lot of time, throws the next error:
![image](https://user-images.githubusercontent.com/46456105/148801976-2e492c8d-d4fb-42ac-80bc-bb5ad931b7e3.png)

**Comment by byCedric** [comment]
Hi @kuriel-trivu! Can you share the project? It seems like Metro is somehow stuck building your app. It can have multiple causes, like unintended inclusion of a lot of files etc.

**Comment by byCedric** [comment]
Closing due to inactivity, if you still comment what I asked for, please mention me 😄

**Comment by endronk** [comment]
I also got the same error. This is my yaml file
```
name: Expo Production Publish
on:
  push:
    branches:
      - release-v*
    paths:
      - "**.js"
jobs:
  publish:
    name: 🚀 Build and Publish (OTA Update)
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Publish app
        run: expo publish --non-interactive --release-channel=${GITHUB_REF_NAME}
```

But, I can't share my project because it's company project. What should I do?
