### ISSUE TITLE
Add eas.json contents as step output

### ISSUE THREAD

**Issue by thgh** [expo/expo-github-action#155]
### Description of the feature
The action could output the eas.json contents so it can be reused by other steps

### Motivation
I would like to use `expo publish` to the production release channel

### Additional context
This is my current workaround:

```
      - name: 🏗 Release channel
        uses: sergeysova/jq-action@v2
        id: releaseChannel
        with:
          cmd: 'jq .build.production.releaseChannel eas.json -r'

      - name: 🚀 Publish app
        run: expo publish --non-interactive --release-channel=${{ steps.releaseChannel.outputs.value }}
```
