### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by mwillbanks** [expo/expo-github-action#158]
### Description of the bug
How would you shortly summarise the issue?

The runner simply fails with Unexpected end of JSON input.

### To Reproduce
What steps did you perform which led to this issue?

Github action setup as following:

```
name: Pull Request
on: [pull_request]

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2
      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-cache: true
          expo-version: 6.x
          token: ${{ secrets.EXPO_TOKEN }}
```

#### Expected behavior
What did you expect to have happened?

The action wouldn't fail but rather run.

#### Actual behavior
What did it actually result in?

Unexpected end of JSON input

### Additional context
Can you further explain the issue? E.g., information about version/environment or screenshots.

This is a new project, everything is setup currently to work for expo and upon a PR request the action fails with the above behavior.  Nothing to really add.
