### ISSUE TITLE
Issue with Expo 5.3.0 update

### ISSUE THREAD

**Issue by PatrickCleary** [expo/expo-github-action#167]
### Description of the bug
How would you shortly summarise the issue?
When expo upgraded to 5.3.0 my deployments began failing with:

```
Run expo/expo-github-action@v5
Installing Expo CLI (5.3.0) from cache or with npm
Error: Error: EACCES: permission denied, copyfile '/home/runner/work/_temp/_github_home/.aws/amplify/deployment-secrets.json' -> '/opt/hostedtoolcache/expo-cli/5.3.0/x64/_github_home/.aws/amplify/deployment-secrets.json'
```

I'm not sure if it is only an issue with AWS Amplify or not. 

### To Reproduce
What steps did you perform which led to this issue?

GitHub action configuration: 
```
  - uses: expo/expo-github-action@v5
        with:
          expo-packager: npm
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
```

#### Expected behavior
What did you expect to have happened?
configure Expo within action

#### Actual behavior
What did it actually result in?
The error posted above
### Additional context
Can you further explain the issue? E.g., information about version/environment or screenshots.
Updated my configuration to:

```
  - uses: expo/expo-github-action@v5
        with:
          expo-packager: npm
          **expo-version: 5.2.0**
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
```
          
          And my deployments began succeeding again.

**Comment by PatrickCleary** [comment]
Not urgent or anything, the work around I have is fine. Just thought I would let the developers know. Sorry for lack of details.

**Comment by byCedric** [comment]
Hi @PatrickCleary! I'm not exactly sure what's going on with the amplify stuff. I don't think we are calling amplify in any way, so it's probably a dependency to run the project (if it contains amplify). If your project is calling it, then I don't know why it's picking the Expo CLI's version of amplify.

That being said, the [latest e2e tests](https://github.com/expo/expo-github-action/actions/runs/2000588011) for version `v7` (or `7.1.1` exactly) shows that you can install `expo-cli@5.3.0` without issues using either npm or yarn. So I would recommend upgrading your version to v7. Heads up, there are slightly different settings with the newer version:

### expo/expo-github-action@v5
```
  - uses: expo/expo-github-action@v5
    with:
      expo-packager: npm
      expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
      expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      expo-cache: true
``` 

### expo/expo-github-action@v7
```
  - uses: expo/expo-github-action@v7
    with:
      packager: npm
      token: ${{ secrets.EXPO_TOKEN }}
``` 

In v7:
- `expo-packager` has been renamed to `packager` because this also applies to installing `eas-cli`
- `expo-cache` is now set to `true` by default
- `expo-username|password` has been deprecated since v6, and removed in v7, in favor of [access tokens](https://docs.expo.dev/accounts/programmatic-access/#personal-account-personal-access-tokens) - you can [create yours here](https://expo.dev/accounts/%5Baccount%5D/settings/access-tokens).
