### ISSUE TITLE
EAS update fails every time

### ISSUE THREAD

**Issue by alexreyes** [expo/expo-github-action#174]
### Description of the bug

When the github action for [Publish updates on push](https://docs.expo.dev/eas-update/github-actions/#publish-updates-on-push) runs I get this result: "error: Unable to determine runtime version for android"

### To Reproduce
What steps did you perform which led to this issue?

1. Add EXPO_TOKEN for the repo
2. Create a file path named .github/workflows/update.yml at the root of the project.
3. Copy/paste the code [from the github actions doc](https://docs.expo.dev/eas-update/github-actions/) and follow the directions listed

#### Expected behavior

I expected the build to succeed

#### Actual behavior

<img width="1062" alt="Screen Shot 2022-03-31 at 10 11 34 PM" src="https://user-images.githubusercontent.com/7016669/161198936-83621394-8983-449e-8a48-10e4ab8890da.png">

### Additional context

Here is the full .yml file I am using: 

```
name: update
on: push

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Publish update
        run: eas update --auto
```
