### ISSUE TITLE
Expo setup fails

### ISSUE THREAD

**Issue by orome** [expo/expo-github-action#175]
The Expo setup step fails after "Installing expo-cli (5.3.0) from cache or with yarn" with:

```
Skipped installing eas-cli: 'eas-version' not provided.
[755](https://github.com/orome/learn-rn/runs/5819337239?check_suite_focus=true#step:4:755)
Validating authenticated account
[756](https://github.com/orome/learn-rn/runs/5819337239?check_suite_focus=true#step:4:756)
  /opt/hostedtoolcache/expo-cli/5.3.0/x64/node_modules/.bin/expo whoami
[757](https://github.com/orome/learn-rn/runs/5819337239?check_suite_focus=true#step:4:757)
  [15:37:30] Request failed with status code 401
[758](https://github.com/orome/learn-rn/runs/5819337239?check_suite_focus=true#step:4:758)
  [15:37:30] Error: Request failed with status code 401
[749](https://github.com/orome/learn-rn/runs/5819337239?check_suite_focus=true#step:4:749)
      at createError (/opt/hostedtoolcache/expo-cli/5.3.0/x64/node_modules/axios/lib/core/createError.js:16:15)
[750](https://github.com/orome/learn-rn/runs/5819337239?check_suite_focus=true#step:4:750)
      at settle (/opt/hostedtoolcache/expo-cli/5.3.0/x64/node_modules/axios/lib/core/settle.js:17:12)
[751](https://github.com/orome/learn-rn/runs/5819337239?check_suite_focus=true#step:4:751)
      at IncomingMessage.handleStreamEnd (/opt/hostedtoolcache/expo-cli/5.3.0/x64/node_modules/axios/lib/adapters/http.js:260:11)
[752](https://github.com/orome/learn-rn/runs/5819337239?check_suite_focus=true#step:4:752)
      at IncomingMessage.emit (node:events:538:35)
[753](https://github.com/orome/learn-rn/runs/5819337239?check_suite_focus=true#step:4:753)
      at endReadableNT (node:internal/streams/readable:1345:12)
[754](https://github.com/orome/learn-rn/runs/5819337239?check_suite_focus=true#step:4:754)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
[755](https://github.com/orome/learn-rn/runs/5819337239?check_suite_focus=true#step:4:755)
Error: The process '/opt/hostedtoolcache/expo-cli/5.3.0/x64/node_modules/.bin/expo' failed with exit code 1
```

**Comment by byCedric** [comment]
Hi @orome! Can you share your workflow file? It seems that the `EXPO_TOKEN` you used is invalid and therefore triggers a `401` response from our API. It means that you are not allowed to fetch the current username (usually because the token is invalid).

**Comment by orome** [comment]
@byCedric Any ideas what could be causing it to be invalid? I've checked and rechecked and the value I save as a secret in the repo is the same as the value of the secret in the Expo project. Could I be failing to meet some requirement on the form of the token?

**Comment by orome** [comment]
@byCedric I've quadruple checked and the `EXPO_TOKEN` GitHub repo secret has exactly the same value and the Expo project's secret (in the project's secrets setting).

```
name: Expo Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Publish app
        run: expo publish --non-interactive
```
