### ISSUE TITLE
workspaces support: code EWORKSPACESCONFIG workspaces config expects an Array

### ISSUE THREAD

**Issue by AronBe** [expo/expo-github-action#179]
### Description of the bug
```
 "workspaces": {
    "nohoist": [
      "**"
    ]
  }
```

Using object on `workspaces` in `package.json` probably breaks some expected schema when triggering `npx eas-cli build --profile production --platform all --auto-submit --non-interactive --no-wait`. Somewhat similar to [this issue](https://github.com/microsoft/vscode/issues/77912). The object is ok to use per [yarn](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) but array is expected with GA, locally I don't have issues running EAS.

**github action**
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_ACCESS_TOKEN }}

      - name: 📦 Install dependencies
        working-directory: mobile
        run: yarn install

      - name: Build and Submit on EAS
        working-directory: mobile
        run: npx eas-cli build --profile production --platform all --auto-submit --non-interactive --no-wait
```

### To Reproduce
In Monorepo child app add following to `package.json`
```
 "workspaces": {
    "nohoist": [
      "**"
    ]
  }
```

#### Expected behavior
EAS build should get triggered from Github Action

#### Actual behavior
![image](https://user-images.githubusercontent.com/32416348/164464325-9bcb3304-4bb5-456b-ae1a-ce2527309cc5.png)
