### ISSUE TITLE
Upgrade to latest GitHub Actions version

### ISSUE THREAD

**Issue by byCedric** [expo/expo-github-action#18]
### Topic and scope of discussion
A summary of all changes to upgrade Expo GitHub Actions to the latest Actions version.

### Motivation
From 30 Sept 2019 the old HCL syntax of GitHub Actions is deprecated. That means we have to upgrade the documentation and see if we need to make additional changes to the project.

### Additional context
- [ ] Research about `Docker` vs `JavaScript` actions
- [ ] Research `runs` vs `args` notations in YAML
- [ ] Replace old Docker-label metadata with YAML

**Comment by byCedric** [comment]
Ok, so here are some things I learned from testing the latest GitHub Actions syntax:

1. You can pick your own operating system (`linux`, `macos` and `windows`)
2. Matrix builds are actually pretty well done, you can use them as simple variables within your workflow
3. Actions do either a simple thing or install a library to use later on in the steps

Below I wrote two approaches, I think **Approach 1 - `setup-expo`** should enable us to do anything we want. But it removes the need for containers, which some of the developers (like me) actively use. Then again, we can split this out to a separate repository or project.

### Approach 1 - `setup-expo`

With this in mind, I think we need to change this library quite a bit. Using containers with Expo pre-installed is kind of restricting when picking different operating systems. So we might need to use the same approach of [`actions/setup-node`](https://github.com/actions/setup-node), but for Expo.

We could use the power of yarn/npm and create an action that basically runs `npm install -g expo-cli@${expo-version}`. But I'm not sure what that will do with performance.

```yaml
steps:
  - uses: expo/expo-github-action@4
    with:
      version: 3.0.x
      username: bycedric
      password: ${secrets.EXPO_PASSWORD}
  - run: expo install
  - run: expo publish
```

With the "old" structure we had the benefit of running Expo directly, without having to install it. But I think this is now obsolete because of the flexibility of the new GH action system.

### Approach 2 - `contained expo`

An alternative would be to keep using containers. It gives us the benefit of not having to install expo every time we run the workflow. But it restricts us in changing to different operating systems.

```yaml
steps:
  - uses: expo/expo-github-action@4
    with:
      command: install
  - uses: expo/expo-github-action@4
    with:
      command: publish
    env:
      EXPO_CLI_USERNAME: bycedric
      EXPO_CLI_PASSWORD: ${secrets.EXPO_PASSWORD}
```

**Comment by byCedric** [comment]
I've drafted a new version at [`refactor/update-action`](https://github.com/expo/expo-github-action/tree/refactor/update-action)! Currently, it's working, but I'm not happy about the performance. We definitely need a way to cache the installed Expo files, but unfortunately, [there is none (yet)](https://github.com/actions/toolkit/issues/47). 

I prefer to wait to release this version when they have this implemented, or the HCL syntax is EOL. For now, you can use the new action by specifying the branch name. I'll update the documentation when I get some time available again.

Also, another heads up, the Docker images are dropped in this version. Because I (and the company I work for) use these images, [I moved them to another repository](https://github.com/bycedric/expo-cli-images). It's using the same image name as before but is its own project for now.

**Comment by Kampe** [comment]
For anyone who comes accross this until there's a fix passing the argument has to be sent with "args" not "command" 

```
steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm install
      - name: Publish to Expo
        uses: docker://bycedric/expo-cli:3
        with:
          args: publish
        env:
          EXPO_CLI_USERNAME: ${{secrets.EXPO_CLI_USERNAME}}
          EXPO_CLI_PASSWORD: ${{secrets.EXPO_CLI_PASSWORD}}
```

**Comment by byCedric** [comment]
Thanks for the solution ❤️ I like the approach of using the docker image within the new GH Actions syntax, but remember there are some functionality that you lose (like using windows/mac as OS). The approach you use is solid and will still work after we release the updated version, or when GH pulls the plug on their HCL syntax end of this month.

I have updated the action to the new yml format, basically it installs the requested version that you want on the system you use (e.g. `ubuntu-latest`, `macos-latest` or `windows-latest`). Due to the fact that Github does not support proper caching across jobs, I've hold back this update. Could you try if the new one works without issues on your setup? Here is some basic configuration you can use that _**should** work out of the box_.

```yml
name: New Expo Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Setup Expo CLI 3.x
        uses: expo/expo-github-action@refactor/update-action
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Install Dependencies
        run: npm install
      - name: Publish to Expo
        run: expo publish
```

If you are curious and want to go all the way, here is a slightly modified version that uses ubuntu, macos and windows for node 10 and 12 and all using both npm _and_ yarn. I wouldn't recommend publishing from all these jobs, but you can perform the tests on all of them for example. It should help you make sure nothing breaks on any combination of all these system conditions (useful for large teams with mixed dev machine types 😄).

```yml
name: New Expo Action on Steroids
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10, 12]
        packager: [npm, yarn]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Setup Expo CLI 3.x
        uses: expo/expo-github-action@refactor/update-action
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-packager: ${{ matrix.packager }}
      - name: Install Dependencies
        run: npm install
      - name: Test Expo app
        run: npm test
```
