### ISSUE TITLE
Capitalization isn't honored in GitHub actions

### ISSUE THREAD

**Issue by robertjcolley** [expo/expo-github-action#188]
### Description of the bug
How would you shortly summarise the issue?

I have a project named `RepPacer`. When using `expo publish` from my mac, the URL generated honors the capitalization from the project. I believe the generated QR code doesn't honor the capitalization of my project name.

### To Reproduce
What steps did you perform which led to this issue?

1. create expo project with uppercase letters
2. `expo publish`
3. validate url has uppercase and project id is uppercase
4. push to github
5. set up github actions for `main` branch to publish on PR's
6. make a new PR
7. observe generated QR code doesn't link to project 
8. observe project slug in comment doesn't honor capitalization

#### Expected behavior
What did you expect to have happened?

- The QR code should link to the capitalized name project
- The project slug should have the capitalized name project

<img width="856" alt="Screen Shot 2022-07-02 at 10 58 22 AM" src="https://user-images.githubusercontent.com/29097404/177005806-0a612018-1505-4f92-a766-0a25261e3687.png">

##### Correct URL

exp://exp.host/@rc04/RepPacer?release-channel=pr-3

#### Actual behavior
What did it actually result in?

![IMG_B05A35C7EB06-1](https://user-images.githubusercontent.com/29097404/177005861-612b6a0c-ad79-46d6-b6a6-9695861b616f.jpeg)

### Additional context
Can you further explain the issue? E.g., information about version/environment or screenshots.

#### Pull Request Template

```yml
on: [pull_request]
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Publish preview
        run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive

      - name: 💬 Comment preview
        uses: expo/expo-github-action/preview-comment@v7
        with:
          channel: pr-${{ github.event.number }}
```
