### ISSUE TITLE
Expo publish & preview action is very slow

### ISSUE THREAD

**Issue by Dakuan** [expo/expo-github-action#190]
### Description of the bug
exp publish is taking ~30mins to build a PR, seems to have happened in a recent expo update. Its less than a minute on my local machine (M1 macbook pro). As a result, all of our github minutes get munched in the first 48 hours of the month, making previews impossible.

### To Reproduce
this is our github action config:

```
name: Create preview
on: [pull_request]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2
      
      - name: Add Fortawesome token to npmrc
        run: echo -e "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_AUTH_TOKEN }}" > .npmrc

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - run: rm  ./assets/db/birda_geo_9.db.zip
      - run: mv ./assets/db/dummy.txt ./assets/db/birda_geo_9.db.zip

      - name: 🚀 Publish preview
        run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive
        env:
          EXPO_USE_DEV_SERVER: true
          ENABLE_NOTICES: true
          ENABLE_AUTH_PROXY: true
          ENABLE_PRIVACY_CONTROLS: true
          SKIP_ZIP: true

      - name: 💬 Comment preview
        uses: expo/expo-github-action/preview-comment@v7
        with:
          channel: pr-${{ github.event.number }}

```
#### Expected behavior
build in a reasonable time frame

#### Actual behavior
ate all my github minutes

### Additional context
slowed down alot with expo 45
