### ISSUE TITLE
Preview action `command` does not allow for environment variables

### ISSUE THREAD

**Issue by zaniluca** [expo/expo-github-action#212]
#### Old version
Currently `expo/expo-github-action/preview` does not allow for environment variables to be passed on the eas update command, the action fails with an error message: 

```
The command must start with "eas", received "SENTRY_DSN=*** \
SENTRY_ORG=*** \
SENTRY_PROJECT=*** \
SENTRY_AUTH_TOKEN=*** \
eas update --auto"
```

#### New version
It would be nice to be able to pass environment variables to the `command` input

### Additional context
I've run into this problem with my codebase while trying to deploy a preview update that needs the injection of some Sentry-related environment variables and I received the error: see [Action Result](https://github.com/zaniluca/ping-4-gitlab/actions/runs/4336709481/jobs/7572196723)

**Comment by georgibakken** [comment]
You can pass env variables and secrets from GitHub actions to the step, example
```
 - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@v8
        env:
          SOME_VAR: ${{ vars.SOME_VAR }}
          SOME_SECRET ${{ secrets.SOME_SECRET }}
        with:
          command: eas update --auto
```

**Comment by zaniluca** [comment]
> You can pass env variables and secrets from GitHub actions to the step, example:
> 
> ```
>  - name: 🚀 Create preview
>    uses: expo/expo-github-action/preview@v8
>    env:
>       SOME_VAR: ${{ vars.SOME_VAR }}
>       SOME_SECRET ${{ secrets.SOME_SECRET }}
>    with:
>       command: eas update --auto
> ```

@georgibakken It seems like it's not correctly injecting the variables, or either it's `eas update` which doesn't pick up environment variables when they're not declared inline

**Comment by georgibakken** [comment]
I also had some issues with it in the beginning, but it seems to work for me. The issues were more on the GitHub actions side, as I had created environments for my secrets and variables, and forgotten to specify the environment in the workflow file 🙈 .

What does your GitHub action log say for the step running `eas update --auto` regarding environments? It should log something like this:
```
Run expo/expo-github-action/preview@v8
  with:
    command: eas update --auto
    github-token: ***
  env:
    EXPO_TOKEN: ***
    SOME_VAR: some_var
    SOME_SECRET: ***
```
