### ISSUE TITLE
Allow for setting environment variables when running EAS command

### ISSUE THREAD

**Issue by lpatino10** [expo/expo-github-action#223]
### Description of the feature
As far as I can tell, when using the EAS CLI to create an update, the only way to set environment variables is to [prepend them to the command](https://docs.expo.dev/eas-update/environment-variables/#setting-and-getting-environment-variables-when-publishing-an-update). This does not appear to be possible with the `expo-github-action/preview` subaction.

### Motivation
In my case, I'm using [Tamagui](https://tamagui.dev/) in my project, which requires a `TAMAGUI_TARGET` environment variable when building to transform primitives to native or web ones. Unfortunately, if I want to implement the [PR preview flow](https://docs.expo.dev/eas-update/github-actions/#publish-previews-on-pull-requests) using this subaction, I can't set that.

I imagine there are other use-cases where having environment variables present might be important.

### Additional context
Below is a screenshot of an example run where I try prepending the environment variable to the `eas update` command:

<img width="800" alt="Screen Shot 2023-06-23 at 5 29 42 PM" src="https://github.com/expo/expo-github-action/assets/8710772/696c5ebb-f5d0-44df-b5bc-ba0bb35f362a">

**Comment by danielgangverk** [comment]
I have this configuration and environment variables are working for me:

```yaml
.. rest of yaml

      - name: 💬 Comment preview
        uses: expo/expo-github-action/preview@v8
        env:
          YOUR_ENV_VARIABLE_HERE: 'this is a test value'
        with:
          comment: true
          command: eas update --auto --non-interactive
          comment-id: auto-preview
```

I ran into the same issues as you when trying to prepend the env variable. IIRC the env variables also didn't work unless I was using the `--auto` flag
