### ISSUE TITLE
Pull request eas update wrong branch name

### ISSUE THREAD

**Issue by homburg** [expo/expo-github-action#229]
### Description of the bug
Using the preview github actions recipe produces `HEAD` expo branch name.

### To Reproduce
Set up preview update builds on pull request action.

```
name: "Preview Pull Request"
on:
  pull_request:

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - run: yarn

      - name: Generate runtime version
        run: ./scripts/generate-app-json.sh

      - uses: expo/expo-github-action/preview@v8
        env:
          APP_PR_PREVIEW: "true"
        with:
          command: eas update --auto
```

#### Expected behavior

Expected updates to be pushed to expo.dev with the pull request branch name, eg `abc-1232-my-feature`

#### Actual behavior

Got updates pushed to expo.dev with `HEAD` branch name.

<img width="1152" alt="image" src="https://github.com/expo/expo-github-action/assets/235886/66f3df7b-bdec-466f-bc33-f22cfde1dec9">

### Additional context

I think this is because github actions by default works on merge commit when triggered by the `pull_request` event.

### My current work-around

I worked around this by changing github actions checkout to check the pull request head branch out instead of default merge behavior

```
      - uses: actions/checkout@v3
        with:
          # Checkout branch instead of automatic merge commit
          ref: ${{ github.event.pull_request.head.ref }}
```
