### ISSUE TITLE
Setup takes extra time

### ISSUE THREAD

**Issue by FaureAlexis** [expo/expo-github-action#250]
Hey !
### Description of the bug

When I setup EAS, the step takes extra times (~1-2mn which is quite something) and I don't know why

### To Reproduce

1 - Add a step to a Github Action job :
```yaml
     - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm
          patch-watchers: false
```

2 - Trigger the workflow

#### Expected behavior

Expect job to succeed after `Skipped patching watchers: 'patch-watchers' disabled.`

#### Actual behavior

After `Skipped patching watchers: 'patch-watchers' disabled.`, the job wait for 1-2mn.

Output : 
![image](https://github.com/expo/expo-github-action/assets/75880156/86fdea14-ed12-4c8e-857f-7e2ff7fac64e)

### Additional context
Can you further explain the issue? E.g., information about version/environment or screenshots.

Maybe it's normal, maybe it's not...
Ty for your help
