### ISSUE TITLE
Global `working-directory` config not used in `expo-github-action/preview`

### ISSUE THREAD

**Issue by axeldelafosse** [expo/expo-github-action#266]
### Description of the bug
When using `expo-github-action/preview` with a monorepo, the global `working-directory` isn't used.

### To Reproduce
It looks like this config is not used:
```
defaults:
  run:
    working-directory: apps/expo
```

I had to specify the directory again:
```
- name: 🚀 Create preview
    uses: expo/expo-github-action/preview@v8
    with:
      command: eas update --auto --branch pr-${{ steps.PR.outputs.number }}
      working-directory: apps/expo
```

#### Expected behavior
We probably shouldn't have to specify the `working-directory` again.

#### Actual behavior
We have to specify the `working-directory` when using `expo-github-action/preview`
