### ISSUE TITLE
continuous-deploy-fingerprint error: The process '/usr/local/bin/npx' failed with exit code 1

### ISSUE THREAD

**Issue by yannikreiter-maxworx** [expo/expo-github-action#296]
### Description of the bug
Using the [continous-deploy-fingerprint](https://github.com/expo/expo-github-action/tree/main/continuous-deploy-fingerprint) sub action as described in the [sample workflow](https://github.com/expo/expo-github-action/tree/main/continuous-deploy-fingerprint#example-workflows) causes the following error:
`Error: Could not get fingerprint for project: Error: The process '/usr/local/bin/npx' failed with exit code 1`

### To Reproduce
1. Create GitHub Actions workflow based on the sample
2. Create pull request

#### Expected behavior
Based on the fingerprint, either an update is published or new build is started.

#### Actual behavior
The "Continuously Deploy" step fails.

### Additional context
This is my YAML file, slightly altered from the sample:
- Use staging branch instead of main
- Remove test job
- Use npm instead of yarn
- Use development-preview as profile and branch

```yaml
on:
  push:
    branches:
      - staging
  pull_request:
    types: [opened, synchronize]

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  continuously-deploy:
    runs-on: ubuntu-latest
    concurrency: continuous-deploy-fingerprint-${{ github.event_name != 'pull_request' && 'staging' || github.run_id }}
    permissions:
      contents: read # Allow checkout
      pull-requests: write # Allow comments on PRs
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@main
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Continuously Deploy
        uses: expo/expo-github-action/continuous-deploy-fingerprint@main
        with:
          profile: development-preview
          branch: development-preview
```
