### ISSUE TITLE
continuous-deploy-fingerprint "could not run command eas build"

### ISSUE THREAD

**Issue by Wolfleader101** [expo/expo-github-action#297]
### Description of the bug
I seem to be getting this error with my continuous deployment.
It only seems to be happening on the ios build, as it builds android just fine.

![image](https://github.com/user-attachments/assets/786542c2-00ab-4c0d-be46-743bc11d7193)

### To Reproduce
This is my action
```yml
name: continuously-deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  continuously-deploy:
    runs-on: ubuntu-latest
    concurrency: continuous-deploy-fingerprint-${{ github.event_name != 'pull_request' && 'main' || github.run_id }}
    permissions:
      pull-requests: write # Allow comments on PRs
      actions: write # Allow updating fingerprint in action caches
      contents: read # Allow checkout
      packages: write # Allow caching

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: 📦 Install dependencies
        run: cd apps/expo && pnpm install

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@main
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Continuously Deploy
        uses: expo/expo-github-action/continuous-deploy-fingerprint@main
        with:
          working-directory: apps/expo
          profile: ${{ github.event_name != 'pull_request' && 'production' || 'preview' }}
          branch: ${{ github.event_name != 'pull_request' && 'production' || 'preview' }}
```
