### ISSUE TITLE
eas build - Service Unavailable

### ISSUE THREAD

**Issue by TheAdamBorek** [expo/expo-github-action#330]
### Description of the bug
When we run  `eas build --platform all --non-interactive --wait --profile production --auto-submit`

We receive nearly immediately the following error:
![Image](https://github.com/user-attachments/assets/22597516-157b-4c3a-bc5c-eda722284cd0)
The error message is ambiguous and doesn't allow me to search for possible fixes.

### To Reproduce
- Run the above command as github action
.dev
#### Expected behavior
- To trigger a build on expo

#### Actual behavior
- Error without triggering a build on expo.dev

### Additional context

We use the latest `eas`:
```yml
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
```

I successfully triggered a build from my local mac running `eas build --platform android --non-interactive --wait --profile production. 
On the first attempt, I got the same error as on CI but the next attempt succeeded. This leads me that this could be an issue with `expo-github-action`
