### ISSUE TITLE
Fingerprint cache is not being saved (fingerprint-db)

### ISSUE THREAD

**Issue by alansikora** [expo/expo-github-action#336]
### Description of the bug

Fingerprint cache (fingerprint-db) is not found.

### To Reproduce

Run a simple Github Action with:

```yaml
jobs:
  fingerprint:
    runs-on: ubuntu-latest
    # REQUIRED: limit concurrency when pushing main(default) branch to prevent conflict for this action to update its fingerprint database
    concurrency: fingerprint-${{ github.event_name != 'pull_request' && 'main' || github.run_id }}
    permissions:
      # REQUIRED: Allow comments of PRs
      pull-requests: write # Allow comments on PRs
      # REQUIRED: Allow updating fingerprint in action caches
      actions: write
      # OPTIONAL: Allow reading of repo contents for private projects
      contents: read

    steps:
      - name: 📦 Enable corepack
        run: corepack enable

      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: 📦 Install dependencies
        run: yarn install --immutable

      - name: Check fingerprint
        id: fingerprint
        uses: expo/expo-github-action/fingerprint@main
        with:
          working-directory: ./domain/exchange/mobile
```

There are not logs that would suggest a cache is being saved.

![Image](https://github.com/user-attachments/assets/7842a2b0-e99f-4a64-827c-17a20992335b)

#### Expected behavior

Cache should exist in subsequent runs.

#### Actual behavior

Cache does not exist in subsequent runs.
