### ISSUE TITLE
Error expo/expo-github-action@v5

### ISSUE THREAD

**Issue by dougg0k** [expo/expo-github-action#51]
Hi,

I've been using this action without any problems and today after a push, I got this error, no config was modified.

```
 Run expo/expo-github-action@v5
1m 18s
##[error]Error: The process '/opt/hostedtoolcache/expo-cli/3.21.9/x64/node_modules/.bin/expo' failed with exit code 1
Run expo/expo-github-action@v5
restoring cache /opt/hostedtoolcache/expo-cli/3.21.9/x64
primary key expo-cli-linux-x64-yarn-3.21.9
/bin/tar -xz -f /home/runner/work/_temp/5b65a535-c2cf-4ab0-bace-5a3d286c2909/cache.tgz -C /opt/hostedtoolcache/expo-cli/3.21.9/x64
Cache restored from key: expo-cli-linux-x64-yarn-3.21.9
/opt/hostedtoolcache/expo-cli/3.21.9/x64/node_modules/.bin/expo login --username=***
[16:43:27] Request failed with status code 504
[16:43:27] Error: Request failed with status code 504
    at createError (/opt/hostedtoolcache/expo-cli/3.21.9/x64/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/hostedtoolcache/expo-cli/3.21.9/x64/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/hostedtoolcache/expo-cli/3.21.9/x64/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
##[error]Error: The process '/opt/hostedtoolcache/expo-cli/3.21.9/x64/node_modules/.bin/expo' failed with exit code 1
```
This is the job
```
  publish:
    name: Install and publish changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - run: npm install
      - run: npm run publish
```
Edit:
After a rerun, it run fine, probably related to Expo servers.
