### ISSUE TITLE
Publish performance?

### ISSUE THREAD

**Issue by bradbumbalough** [expo/expo-github-action#58]
This isn't a bug per se, but I wondered if there are any recommendations for publish performance? My last build with the action took 23 minutes. The same publish locally takes maybe 2 minutes.

**Comment by brentvatne** [comment]
hey @bradbumbalough! you could try setting the `EXPO_USE_DEV_SERVER` environment variable in your ci environment, this will switch to using the metro js api directly rather than starting react-native-cli and then building from there. this should be faster for a variety of reasons, give it a shot and let us know. we plan to switch this to the default behavior soon.

related tweet: https://twitter.com/expo/status/1293613036482121728

**Comment by bradbumbalough** [comment]
Hey @brentvatne!! Thanks for the tip.. I'm trying it out now and will update what I find.

**Comment by bradbumbalough** [comment]
It cut the time in half! down to 10 minutes. Maybe that is attributed to the CPU availability on GH.

**Comment by giautm** [comment]
Hey @brentvatne, I have the same issues with Expo Github Actions. It takes 16m to complete. (7m for local).

<img width="1041" alt="Screen Shot 2021-05-03 at 17 58 29" src="https://user-images.githubusercontent.com/12751435/116868585-3c513380-ac39-11eb-8e92-3d80e8238d02.png">

**Comment by brentvatne** [comment]
this looks like it may have been an issue with the machine the github action is running, sorry i'm not really sure. we just get the bundle from metro and upload it.

**Comment by giautm** [comment]
I think the publish time may be related to Metro cache config; likely on the Github actions, there is no cache config?

How I can config Metro's `cacheStores` with expo-cli? https://facebook.github.io/metro/docs/caching

**Comment by giautm** [comment]
Fixed, I used the two steps below to restore the react-native metro cache. So, It speed-up publish time to 1m6s. You can remove `${{ matrix.app }}` from the below script if you have only one app/repo.
<img width="859" alt="Screen Shot 2021-05-05 at 16 15 05" src="https://user-images.githubusercontent.com/12751435/117121034-494b5f80-adbe-11eb-802b-8360810bf00b.png">

```yml
      # Restore react-native metro cache for speed-up publish time
      # See: https://github.com/facebook/metro/blob/7dca99af2e2af17921aa4a1e16b1972adc0d11e4/packages/metro-config/src/defaults/index.js#L121-L125
      - name: Find Metro cache
        id: metro-cache-dir-path
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const os = require('os');
            const path = require('path');
            return path.join(os.tmpdir(), 'metro-cache');
      - name: Restore Metro cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.metro-cache-dir-path.outputs.result }}
          key: ${{ runner.os }}-metro-cache-${{ matrix.app }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-metro-cache-${{ matrix.app }}-${{ github.base_ref }}
            ${{ runner.os }}-metro-cache-${{ matrix.app }}-
```

**Comment by jonnyasmar** [comment]
> Fixed, I used the two steps below to restore the react-native metro cache. So, It speed-up publish time to 1m6s. You can remove `${{ matrix.app }}` from the below script if you have only one app/repo.

From ~20 mins to publish to ~30 seconds. Beautiful fix! 👏

Thank you!

**Comment by jojonicho** [comment]
Any gitlab-ci.yml version of the fix above? Much appreciated

**Comment by Stevemoretz** [comment]
I too need gitlab-ci.yml version of the fix above

**Comment by Stevemoretz** [comment]
I figured out how to change the cache path, create a metro.config.js:

```js
const path = require("path");
const {getDefaultConfig} = require("expo/metro-config");

const config = getDefaultConfig(__dirname);

if (process.env.METRO_CUSTOM_CACHE_PATH) {
    const oldCachePath = config.cacheStores[0]._root;
    config.cacheStores[0]._root = path.resolve(
        process.env.METRO_CUSTOM_CACHE_PATH
    );
    console.log(
        `metro cache was changed from "${oldCachePath}" to "${config.cacheStores[0]._root}"`
    );
}

module.exports = config;
```

With this you'll be able to use METRO_CUSTOM_CACHE_PATH environment variable to set a custom path eg:
```bash
 METRO_CUSTOM_CACHE_PATH="./metro" expo start
```
which would give:

```
Starting project at /Volumes/HDD/ReactNative/...
Developer tools running on http://localhost:19002
metro cache was changed from "/var/folders/nf/6q0rl3v91yj3tvfvnjxxws9r0000gn/T/metro-cache" to "/Volumes/HDD/ReactNative/.../metro"
Starting Metro Bundler
```

> I think the publish time may be related to Metro cache config; likely on the Github actions, there is no cache config?
> 
> How I can config Metro's `cacheStores` with expo-cli? https://facebook.github.io/metro/docs/caching

@giautm  Now this, lets you create a faster Github action.

> Any gitlab-ci.yml version of the fix above? Much appreciated

@jojonicho  Here's a gitlab equivalent using my solution :

```yml
.metro-cache: &metro-cache
  key: metro-cache-$CI_JOB_IMAGE
  paths:
    - metro
  policy: pull

release-update:
  stage: release
  cache:
    - <<: *metro-cache
      policy: pull-push
  script:
    - yarn install
    - npx expo publish --non-interactive
    - ls -l metro
  only:
    - tags
``` 

Of course you might as well, cache yarn install and put it in another stage. ( I didn't want to complicate the example ).

-----
@brentvatne 
You might want to add this feature directly inside `expo/metro-config`.

**Comment by Stevemoretz** [comment]
Sharing the results of my solution on gitlab : 

First time (before caching):
Duration: 18 minutes 42 seconds

Second time (after the cache was created):
Duration: 4 minutes 30 seconds

**Comment by swushi** [comment]
Just wanted to share my solution as well, this gets it down to `~30s` and is a little simpler IMO. 

You can simply specify any directory as the temp directory with the environment var, `TMPDIR`, which metro references.

```yml
jobs:
  e2e:
    runs-on: macos-11

    env:
      TMPDIR: /tmp # Used for metro caching

    steps:
      - name: Cache Metro
        uses: actions/cache@v3
        id: cache-metro
        with:
          path: |
            ${{ env.TMPDIR }}/metro-cache
            ${{ env.TMPDIR }}/haste-map*
          key: npm-${{ env.NODE_VERSION }}-${{ runner.os }}

```

**Comment by yonitou** [comment]
Hey

Jumping on this thread because I'm experiencing very slow publish times with GitLabCI. I used @Stevemoretz workaround but can't success to make it work. I can see that my custom metro-config is correcty applied because I can see the metro folder being created (I also gitignored it).

```
# Cache node modules - speeds up future builds
cache:
    paths:
        - node_modules

variables:
    NX_METRO_CUSTOM_CACHE_PATH: ./metro

stages:
    - publish

.distributed:
  image: node:16
  interruptible: true
  only:
    - develop
    - release

  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline --legacy-peer-deps
  artifacts:
    paths:
      - node_modules/.cache/nx

.develop:
  before_script:
    - export NX_ENV="staging"
  only:
    - develop

.release:
  before_script:
    - export NX_ENV="production"
  only:
  - release

.metro-cache: &metro-cache
  key: metro-cache-$NX_BASE
  paths:
    - metro
  policy: pull

publish_develop:
    stage: publish
    cache:
      - <<: *metro-cache
        policy: pull-push
    extends: .distributed
    before_script:
        - !reference [.distributed, before_script]
        - !reference [.develop, before_script]
    script:
        - npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=publish --parallel=3 --configuration=staging --exclude=dashboard
    only:
      - develop

publish_release:
    stage: publish
    extends: .distributed
    before_script:
        - !reference [.distributed, before_script]
        - !reference [.release, before_script]
    script:
        - npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=publish --parallel=3 --configuration=production --exclude=dashboard
    only:
      - release
```
