### ISSUE TITLE
running expo build for iOS

### ISSUE THREAD

**Issue by zivl** [expo/expo-github-action#65]
assuming the flow in which expo is taking care of the entire signature and provisioning stuff for you
do you have an example of how to create an `expo build:ios -t archive` flow, which having the Apple Connect user/pass?

**Comment by byCedric** [comment]
Hi @zivl! That should be possible by using environment variables! Based on the [envvars used here](https://github.com/expo/expo-cli/blob/master/packages/expo-cli/src/appleApi/authenticate.ts#L78-L81) and the [options from the command itself](https://github.com/expo/expo-cli/blob/master/packages/expo-cli/src/commands/build/index.ts#L56-L89), it should look something like:

```
name: Build Archive
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: expo build:ios --no-wait --type archive
        env:
          EXPO_APPLE_ID: ${{ secrets.APPLE_ID }}
          EXPO_APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
``` 

You can play around with the options you provide to `expo build:ios`, but the env vars should be enough for you to authenticate. If you have more commands depending on the build or if you want to reflect the GH Action status on a successful build, you can omit `--no-wait` ofc.

Can you try this out? I'll add it to the readme if that works as expected 😄
