### ISSUE TITLE
Running expo on a self hosted servers fails

### ISSUE THREAD

**Issue by Amraneze** [expo/expo-github-action#69]
### Description of the bug
I'm trying to use your Github action on a self hosted server but it fails with this error `EACCES: permission denied`. It's an issue with permission. I added this before running your Github action but I got the same result (following [NPM documentation](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)):

````
      - name: Configure npm
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
````

It might be something related to this function [toLocalCache](https://github.com/expo/expo-github-action/blob/5d3c1cdff4c9e4a57c76c61632398da4d958d974/src/install.ts#L43) from `@actions/tool-cache`

### To Reproduce
>Note: I'm using NodeJs v12.18.3 and npm version 6.14.6

Here is my workflow

````
name: Branch
on:
  push:
    branches-ignore:
      - master

jobs:
  publish:
    name: Install and publish
    runs-on: [self-hosted, linux, x64, aws-production]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # This step is used to configure npm so it can run without
      # getting an issue of "EACCES: permission denied" while
      # installing expo as a global package
      - name: Configure npm
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-token	: ${{ secrets.EXPO_CLI_TOKEN }}
          # Used to keep the dependencies cache
          expo-cache: true
          expo-packager: npm
      - run: npm install
      - run: expo publish
````
#### Expected behavior
To run expo cli and publish the build

#### Actual behavior
The build fails with the following error 

````
Error: Error: EACCES: permission denied, scandir '/home/ubuntu/actions-runner/_work/_temp/_github_home/.docker'
````

### Additional context
It's weird that i'm getting this in the logs

````
npm WARN saveError ENOENT: no such file or directory, open '/home/ubuntu/actions-runner/_work/_temp/package.json'
````

![image](https://user-images.githubusercontent.com/28459763/97363497-f8086380-18a2-11eb-8801-8b6f8e90fcb7.png)

![image](https://user-images.githubusercontent.com/28459763/97363435-e0c97600-18a2-11eb-99f3-24d09fed6619.png)

I used the same command `npm add expo-cli@3.28.2` on GCP server and it works fine 

![image](https://user-images.githubusercontent.com/28459763/97365417-ee342f80-18a5-11eb-846d-910e84cba8a7.png)

I ran it also on a AWS container with the following version and it worked fine too:

#### With NodeJs 15.x & npm 7.x
![image](https://user-images.githubusercontent.com/28459763/97366194-2ee07880-18a7-11eb-92b8-fa899e628552.png)
![image](https://user-images.githubusercontent.com/28459763/97366313-65b68e80-18a7-11eb-9884-67e10b9ad3b4.png)

#### With NodeJs 12.x & npm 6.x
![image](https://user-images.githubusercontent.com/28459763/97367160-eb870980-18a8-11eb-8e88-6727a014b46c.png)
