### ISSUE TITLE
bug: Insecure adding of environment variables

### ISSUE THREAD

**Issue by filiptronicek** [expo/expo-github-action#74]
### Description of the bug
When I run a simple action just setting up Expo and running `expo doctor`, it seems as GitHub is blocking this way of adding environment variables. [GitHub article talking about this](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).

### To Reproduce

1. Make a new GitHub action
2. Paste in the same config as I have

```yaml
name: Expo CI
on: [pull_request]
jobs:
  ci:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, macos-11.0, windows-latest]
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: expo/expo-github-action@5.1.1
        with:
          expo-version: 3.x
      - run: yarn
      - run: expo doctor
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
```

#### Expected behavior
What did you expect to have happened?
A successful `expo doctor` and Expo setup

#### Actual behavior
```log
Error: Unable to process command '::add-path::/opt/hostedtoolcache/expo-cli/3.28.6/x64/node_modules/.bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
[Raw logs](https://pipelines.actions.githubusercontent.com/L1QJjJF3f3zLdUUe5U0HKebzJNyUDXgV9Nvxkji5hJu7TuZwep/_apis/pipelines/1/runs/430/signedlogcontent/8?urlExpires=2021-01-04T09%3A48%3A28.1180522Z&urlSigningMethod=HMACV1&urlSignature=q6E1uCi9m2D7%2B66H9MgZqVxfIoQF%2Fpgjc31mlwB8QcA%3D)
