### ISSUE TITLE
Support Expo staging environment

### ISSUE THREAD

**Issue by IjzerenHein** [expo/expo-github-action#81]
### Description of the feature

Support the Expo staging environment, similar to setting `EXPO_STAGING=1` using the CLI. Currently when using an access_token for the Staging server it fails with:

```
Checking current authenticated account
Error: Error: The process '/opt/hostedtoolcache/expo-cli/4.4.3/x64/node_modules/.bin/expo' failed with exit code 1
```

https://github.com/expo/snack/pull/132/checks?check_run_id=2467846428

*example config*

```
- uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_STAGING }}
          expo-env: staging

```

### Motivation

So we can publish the Snack runtime to both the Staging and Production environments automatically using this github action :)

### Additional context

https://github.com/expo/snack/pull/132

**Comment by IjzerenHein** [comment]
As pointed out by Cedric in this PR, this can already be achieved by setting `STAGING=1` as a global env:

```
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_STAGING: 1
```
