### ISSUE TITLE
Actions on Monorepo

### ISSUE THREAD

**Issue by bearkfear** [expo/expo-github-action#87]
Change de default diferectory

not success after trying alot.

```yml
name: Expo Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - working-directory: app # problably wrong!
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_PAT }}
      - run: yarn install
      - run: expo publish
```
